In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [2]:
df = pd.read_csv("../DSBDAL_Exam_DataSets/Hepatitis/hepatitis.csv", header=None)
df

     0   1   2  3   4  5  6  7  8  9  10 11 12 13    14   15   16   17  18  19
0     2  30   2  1   2  2  2  2  1  2  2  2  2  2  1.00   85   18  4.0   ?   1
1     2  50   1  1   2  1  2  2  1  2  2  2  2  2  0.90  135   42  3.5   ?   1
2     2  78   1  2   2  1  2  2  2  2  2  2  2  2  0.70   96   32  4.0   ?   1
3     2  31   1  ?   1  2  2  2  2  2  2  2  2  2  0.70   46   52  4.0  80   1
4     2  34   1  2   2  2  2  2  2  2  2  2  2  2  1.00    ?  200  4.0   ?   1
..   ..  ..  .. ..  .. .. .. .. .. .. .. .. .. ..   ...  ...  ...  ...  ..  ..
150   1  46   1  2   2  1  1  1  2  2  2  1  1  1  7.60    ?  242  3.3  50   2
151   2  44   1  2   2  1  2  2  2  1  2  2  2  2  0.90  126  142  4.3   ?   2
152   2  61   1  1   2  1  1  2  1  1  2  1  2  2  0.80   75   20  4.1   ?   2
153   2  53   2  1   2  1  2  2  2  2  1  1  2  1  1.50   81   19  4.1  48   2
154   1  43   1  2   2  1  2  2  2  2  1  1  1  2  1.20  100   19  3.1  42   2

[155 rows x 20 columns]

In [3]:
df.columns = ["Class","Age","Sex","Steroid","Antivirals","Fatigue","Malaise","Anorexia","Liver Big","Liver Firm","Spleen","Spiders","Ascites","Varices","Bilirubin","Alk Phosphate","Sgot","Albumin","Protime","Histology"]
df

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anorexia,Liver Big,Liver Firm,Spleen,Spiders,Ascites,Varices,Bilirubin,Alk Phosphate,Sgot,Albumin,Protime,Histology
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,?,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.60,?,242,3.3,50,2
151,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.90,126,142,4.3,?,2
152,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.80,75,20,4.1,?,2
153,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.50,81,19,4.1,48,2
154,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.20,100,19,3.1,42,2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Class          155 non-null    int64
 1   Age            155 non-null    int64
 2   Sex            155 non-null    int64
 3   Steroid        155 non-null    object
 4   Antivirals     155 non-null    int64
 5   Fatigue        155 non-null    object
 6   Malaise        155 non-null    object
 7   Anorexia       155 non-null    object
 8   Liver Big      155 non-null    object
 9   Liver Firm     155 non-null    object
 10  Spleen         155 non-null    object
 11  Spiders        155 non-null    object
 12  Ascites        155 non-null    object
 13  Varices        155 non-null    object
 14  Bilirubin      155 non-null    object
 15  Alk Phosphate  155 non-null    object
 16  Sgot           155 non-null    object
 17  Albumin        155 non-null    object
 18  Protime        155 non-null    object
 19  Histology      155 non-null    int64
dtypes: int64(5), object(15)
memory usage: 24.3+ KB

In [5]:
df.shape

(155, 20)

# Data Cleaning

In [6]:
df.isna().sum()

Class            0
Age              0
Sex              0
Steroid          0
Antivirals       0
Fatigue          0
Malaise          0
Anorexia         0
Liver Big        0
Liver Firm       0
Spleen           0
Spiders          0
Ascites          0
Varices          0
Bilirubin        0
Alk Phosphate    0
Sgot             0
Albumin          0
Protime          0
Histology        0
dtype: int64

In [7]:
df.replace('?',np.nan,inplace=True)
df

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anorexia,Liver Big,Liver Firm,Spleen,Spiders,Ascites,Varices,Bilirubin,Alk Phosphate,Sgot,Albumin,Protime,Histology
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,NaN,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,NaN,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,NaN,1
3,2,31,1,NaN,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,NaN,200,4.0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.60,NaN,242,3.3,50,2
151,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.90,126,142,4.3,NaN,2
152,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.80,75,20,4.1,NaN,2
153,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.50,81,19,4.1,48,2
154,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.20,100,19,3.1,42,2

In [8]:
df.dropna(inplace=True)
df

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anorexia,Liver Big,Liver Firm,Spleen,Spiders,Ascites,Varices,Bilirubin,Alk Phosphate,Sgot,Albumin,Protime,Histology
5,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1
10,2,39,1,1,1,2,2,2,1,1,2,2,2,2,1.30,78,30,4.4,85,1
11,2,32,1,2,1,1,2,2,2,1,2,1,2,2,1.00,59,249,3.7,54,1
12,2,41,1,2,1,1,2,2,2,1,2,2,2,2,0.90,81,60,3.9,52,1
13,2,30,1,2,2,1,2,2,2,1,2,2,2,2,2.20,57,144,4.9,78,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2,45,1,2,1,2,2,2,2,2,2,2,2,2,1.30,85,44,4.2,85,2
143,1,49,1,1,2,1,1,2,2,2,1,1,2,2,1.40,85,70,3.5,35,2
145,2,31,1,1,2,1,2,2,2,2,2,2,2,2,1.20,75,173,4.2,54,2
153,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.50,81,19,4.1,48,2
154,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.20,100,19,3.1,42,2

In [9]:
df.apply(pd.to_numeric,errors='ignore')
df

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anorexia,Liver Big,Liver Firm,Spleen,Spiders,Ascites,Varices,Bilirubin,Alk Phosphate,Sgot,Albumin,Protime,Histology
5,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1
10,2,39,1,1,1,2,2,2,1,1,2,2,2,2,1.30,78,30,4.4,85,1
11,2,32,1,2,1,1,2,2,2,1,2,1,2,2,1.00,59,249,3.7,54,1
12,2,41,1,2,1,1,2,2,2,1,2,2,2,2,0.90,81,60,3.9,52,1
13,2,30,1,2,2,1,2,2,2,1,2,2,2,2,2.20,57,144,4.9,78,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2,45,1,2,1,2,2,2,2,2,2,2,2,2,1.30,85,44,4.2,85,2
143,1,49,1,1,2,1,1,2,2,2,1,1,2,2,1.40,85,70,3.5,35,2
145,2,31,1,1,2,1,2,2,2,2,2,2,2,2,1.20,75,173,4.2,54,2
153,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.50,81,19,4.1,48,2
154,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.20,100,19,3.1,42,2

In [10]:
df.dtypes

Class             int64
Age               int64
Sex               int64
Steroid          object
Antivirals        int64
Fatigue          object
Malaise          object
Anorexia         object
Liver Big        object
Liver Firm       object
Spleen           object
Spiders          object
Ascites          object
Varices          object
Bilirubin        object
Alk Phosphate    object
Sgot             object
Albumin          object
Protime          object
Histology         int64
dtype: object

In [11]:
df=df.astype(float)

# Outliers

In [12]:
df.shape

(80, 20)

In [13]:
out = abs((df - df.mean()) / df.std())
lier = out > 3
lier.sum()

Class            0
Age              0
Sex              0
Steroid          0
Antivirals       0
Fatigue          0
Malaise          0
Anorexia         0
Liver Big        0
Liver Firm       0
Spleen           0
Spiders          0
Ascites          0
Varices          0
Bilirubin        3
Alk Phosphate    1
Sgot             1
Albumin          1
Protime          0
Histology        0
dtype: int64

In [14]:
df = df[~lier.any(axis=1)]
df

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anorexia,Liver Big,Liver Firm,Spleen,Spiders,Ascites,Varices,Bilirubin,Alk Phosphate,Sgot,Albumin,Protime,Histology
5,2.0,34.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.9,95.0,28.0,4.0,75.0,1.0
10,2.0,39.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.3,78.0,30.0,4.4,85.0,1.0
11,2.0,32.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,59.0,249.0,3.7,54.0,1.0
12,2.0,41.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,0.9,81.0,60.0,3.9,52.0,1.0
13,2.0,30.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.2,57.0,144.0,4.9,78.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2.0,45.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.3,85.0,44.0,4.2,85.0,2.0
143,1.0,49.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.4,85.0,70.0,3.5,35.0,2.0
145,2.0,31.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.2,75.0,173.0,4.2,54.0,2.0
153,2.0,53.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.5,81.0,19.0,4.1,48.0,2.0
154,1.0,43.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.2,100.0,19.0,3.1,42.0,2.0

# Data Transformation

In [15]:
num_cols = df.select_dtypes(include=np.number).columns

In [16]:
scaler=StandardScaler()
df[num_cols]=scaler.fit_transform(df[num_cols])
df

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anorexia,Liver Big,Liver Firm,Spleen,Spiders,Ascites,Varices,Bilirubin,Alk Phosphate,Sgot,Albumin,Protime,Histology
5,0.372104,-0.559582,-0.395285,0.921954,0.608581,1.281740,0.714286,0.417855,0.461644,0.897150,0.483046,0.650444,0.372104,0.323230,-0.286348,-0.063141,-0.820889,0.192428,0.461539,-0.802773
10,0.372104,-0.116230,-0.395285,-1.084652,-1.643168,1.281740,0.714286,0.417855,-2.166174,-1.114641,0.483046,0.650444,0.372104,0.323230,0.463731,-0.414608,-0.785887,0.941884,0.892232,-0.802773
11,0.372104,-0.736922,-0.395285,0.921954,-1.643168,-0.780189,0.714286,0.417855,0.461644,-1.114641,0.483046,-1.537412,0.372104,0.323230,-0.098828,-0.807423,3.046821,-0.369664,-0.442915,-0.802773
12,0.372104,0.061111,-0.395285,0.921954,-1.643168,-0.780189,0.714286,0.417855,0.461644,-1.114641,0.483046,0.650444,0.372104,0.323230,-0.286348,-0.352584,-0.260859,0.005064,-0.529053,-0.802773
13,0.372104,-0.914263,-0.395285,0.921954,0.608581,-0.780189,0.714286,0.417855,0.461644,-1.114641,0.483046,0.650444,0.372104,0.323230,2.151409,-0.848772,1.209221,1.878704,0.590747,-0.802773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,0.372104,0.415792,-0.395285,0.921954,-1.643168,1.281740,0.714286,0.417855,0.461644,0.897150,0.483046,0.650444,0.372104,0.323230,0.463731,-0.269886,-0.540874,0.567156,0.892232,1.245682
143,-2.687419,0.770473,-0.395285,-1.084652,0.608581,-0.780189,-1.400000,0.417855,0.461644,0.897150,-2.070197,-1.537412,0.372104,0.323230,0.651251,-0.269886,-0.085849,-0.744392,-1.261231,1.245682
145,0.372104,-0.825593,-0.395285,-1.084652,0.608581,-0.780189,0.714286,0.417855,0.461644,0.897150,0.483046,0.650444,0.372104,0.323230,0.276211,-0.476631,1.716749,0.567156,-0.442915,1.245682
153,0.372104,1.125155,2.529822,-1.084652,0.608581,-0.780189,0.714286,0.417855,0.461644,0.897150,-2.070197,-1.537412,0.372104,-3.093773,0.838771,-0.352584,-0.978398,0.379792,-0.701330,1.245682
154,-2.687419,0.238451,-0.395285,0.921954,0.608581,-0.780189,0.714286,0.417855,0.461644,0.897150,-2.070197,-1.537412,-2.687419,0.323230,0.276211,0.040231,-0.978398,-1.493848,-0.959746,1.245682

In [17]:
df['Class']=np.where(df['Class']>=df['Class'].median(),1,0)

# Model

In [18]:
X = df.drop('Class',axis=1)
Y = df['Class']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [19]:
lr = LogisticRegression()
lr.fit(X_train, Y_train)

LogisticRegression()

In [20]:
pred_lr = lr.predict(X_test)
pred_lr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
pred_lr_acc = accuracy_score(Y_test, pred_lr)
pred_lr_acc

0.8

# Naive Bayes

In [22]:
g_NB = GaussianNB()
g_NB.fit(X_train, Y_train)

GaussianNB()

In [23]:
pred_gnb = g_NB.predict(X_test)
pred_gnb

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [24]:
pred_gnb_acc = accuracy_score(Y_test, pred_gnb)
pred_gnb_acc

0.9333333333333333